### ISSUE TITLE
Support eslint@7

### ISSUE THREAD

**Issue by felipecrs** [oclif/eslint#21]
And probably the latest version of `@typescript-eslint/parser` as well.

![image](https://user-images.githubusercontent.com/29582865/89744508-0bfeaf00-da84-11ea-9dc1-b45ab554bd84.png)

**Comment by seivan** [comment]
Should happen with support for TS 4 now, I find template literal types to be very useful

**Comment by felipecrs** [comment]
Well, support was added alerady, so I'm closing here.

**Comment by seivan** [comment]
@felipecrs What difference does it make when octif relies on older version anyway?

**Comment by felipecrs** [comment]
Of Eslint? Then you should see Eslint 7.0 release notes.

**Comment by felipecrs** [comment]
But the real issue is that it prevents me from upgrading to a newer eslint version if I wanted.
